<?php
//Listado de literales
__( 'Awards', THEME);
__( 'Additional services', THEME);
__( 'Additional service fee', THEME);
__( 'Adults', THEME);
__( 'Adult', THEME);
__( 'Autocaravan', THEME);
__( 'Bookings', THEME);
__( 'Book Now', THEME);
__( 'Car', THEME);
__( 'Caravan', THEME);
__( 'Caravan', THEME);
__( 'Charges per day', THEME);
__( 'Check-in', THEME);
__( 'Check-out', THEME);
__( 'Child', THEME);
__( 'Children', THEME);
__( 'Days', THEME);
__( 'Dogs', THEME);
__( 'Easter', THEME);
__( 'Electricity', THEME);
__( 'Equipment', THEME);
__( 'Follow us', THEME);
__( 'Fridge', THEME);
__( 'High Season', THEME);
__( 'Inventory', THEME);
__( 'Low Season', THEME);
__( 'Medium Season', THEME);
__( 'Motorbike', THEME);
__( 'Night', THEME);
__( 'Nights', THEME);
__( 'Not available', THEME);
__( 'People', THEME);
__( 'Pets', THEME);
__( 'Pitch', THEME);
__( 'Please enter the details of your request', THEME);
__( 'Plot', THEME);
__( 'Price per night', THEME);
__( 'Price per week', THEME);
__( 'Read more', THEME);
__( 'Search', THEME);
__( 'see offer', THEME);
__( 'Small tent', THEME);
__( 'Tent', THEME);
__( 'Teenager', THEME);
__( 'The weather at', THEME);
__( 'Today', THEME);
__( 'Tomorrow', THEME);
__( 'Tourist tax not included', THEME);
__( 'VAT Included', THEME);
__( 'week', THEME);
__( 'years old', THEME);
__( 'last news', THEME);
?>
